### PR TITLE
get_api_cv and routes

### PR DESCRIPTION
**Pull request by kamalrsa**
# Description

Please provide a short summary explaining what this PR is about.
Getapi cv and routes 

Fixes # 5

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by benna100 — COMMENTED** [review]
Have you tested this Kamal? Cause there is no cv table right!?

**Comment by kamalrsa** [comment]
yes kiran is working with CV table and we agreed with the table name and records

**Comment by benna100** [comment]
Ahh okay, i still think we need to merge that PR so you can test if your code works. But super nice with the communication!

Maybe reach out to Kiran and help her get it merged!?

**Comment by benna100** [comment]
These also is a merge conflict you need to fix

**Comment by kamalrsa** [comment]
should I make new PR with issue #5

**Comment by kamalrsa** [comment]
I will make new

**Pull request closed without merging**
