### PR TITLE
patch cvs and controllers

### PR DESCRIPTION
**Pull request by DiegoRuiz454**
# **Description**

PATCH api/cvs/{id} query parameter implemented. cvs.controllers.js and cvs.router.js. the user can edit and update: tilte,createdAt.description,file_url. What if the id does not exists? the following message will appear: CVS ID '${req.params.id}' does not exist.

Fixes # (1)

# **How to test?**

type in the terminal npm run dev. after test it with POSTMAN select PATCH while using the endpoint
http://localhost:5000/api/cvs/{id}.  after that press send. 

# **Checklist**

- [☑] I have performed a self-review of my own code
- [☑] I have commented my code, particularly in hard-to-understand areas
- [☑] I have made corresponding changes to the documentation
- [☑] This PR is ready to be merged and not breaking any other functionality
cvs
cvs 2

### CODE REVIEW

**Comment by h09shais** [comment]
[Build is failing!](https://github.com/HackYourFuture-CPH/rate-my-cv/pull/107/checks?check_run_id=1818922134)

**Comment by DiegoRuiz454** [comment]
> [Build is failing!](https://github.com/HackYourFuture-CPH/rate-my-cv/pull/107/checks?check_run_id=1818922134)

We all have the same error and there is no solution for this error yet. I asked Patrick and he tells me that it is possible to give it like this.

**Comment by shruthidasarapu** [comment]
It looks fine to me.

**Review by pdsorensen — APPROVED** [review]
Looks good. Great job.

**Pull request merged**
