### PR TITLE
Implement changes on HomepageSlogan component...

### PR DESCRIPTION
**Pull request by valmdz**
... so it uses the whole width of the page

# Description

Fix on the Homepage slogan so when integrating it into the Home page, uses the whole width of the page 
Fixes # (issue)

# How to test?

npm run dev
http://localhost:3000/

The home page should look as following:
Screenshot (2638)
Screenshot (2637)

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by dpfernandes — APPROVED** [review]
👍

**Comment by valmdz** [comment]
> 👍

omg you are so fast @dpfernandes

**Comment by shruthidasarapu** [comment]
Looks perfect. Thank  you Valentina.

**Comment by valmdz** [comment]
> Looks perfect. Thank you Valentina.


😉

**Review by pdsorensen — APPROVED** [review]

**Pull request merged**
