### PR TITLE
no footer for sign-up & sign-in

### PR DESCRIPTION
**Pull request by arya56**
# Description
regarding issuer#117
Please provide a short summary explaining what this PR is about.
screen shot before
image

Fixes # (issue)
#117 
# How to test?
Screen shot after
image

if you check those two page shouldn't been seen any footer there
Please provide a short summary how your changes can be tested?
check this url
http://localhost:3000/sign-in
# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Comment by dpfernandes** [comment]
Please consider issues #122 and #123 for this.

**Comment by arya56** [comment]
I think this issue is related to the footer task. Shouldn't have been done within that task?

**Comment by arya56** [comment]
Since I have done it & will be applied to both of issues #122 and #123 . I think it's reasonable for the sake of not doing double job.

**Review by pdsorensen — APPROVED** [review]
I don't understand why we don't want to have a footer all the time. But that's not your responsibility. 

Cheers, this is an acceptable solution 👍

**Comment by pdsorensen** [comment]
@arya56 merge it with develop and i think you can merge it yourself.

**Pull request merged**
