### PR TITLE
Displays 3 latest uploaded cvs

### PR DESCRIPTION
**Pull request by shruthidasarapu**
# Description

Please provide a short summary explaining what this PR is about.

Displays 3 latest uploaded cvs

image

Fixes # (issue)
#issue https://github.com/HackYourFuture-CPH/rate-my-cv/issues/39

# How to test?
npm run storybook
Please provide a short summary how your changes can be tested?

# Checklist

- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [x ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by kamalrsa — COMMENTED** [review]
I couldnot find any errors!! perfect !!

**Review by CharlesKimMaina — COMMENTED** [review]
Looks very fine,. i see in your  storybook that, the 3 last uploaded cvs are shown,.,.

**Review by dpfernandes — CHANGES_REQUESTED** [review]
This component shouldn't have a Title = Latest uploaded Resumes.

This component should render a number of cards defined by the prop inserted so the previous component result should also be able to be rendered which means that it can't include a title.

Check here https://github.com/HackYourFuture-CPH/rate-my-cv/issues/39 and here https://github.com/HackYourFuture-CPH/rate-my-cv/issues/119

**Review by dpfernandes — APPROVED** [review]
👍

**Pull request merged**
