### PR TITLE
Added cvs router and controller files and added route in api-router-js

### PR DESCRIPTION
**Pull request by Kiran-Serolla**
# Description

This PR  is about adding cvs router and controller files to backend and add  a route to api-router.js
Fixes # (issue)

# How to test?

This cannot be tested right now because the migration and seeds are not yet available.

# Checklist

- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by benna100 — CHANGES_REQUESTED** [review]
Can you also add the cvs.router to the api-router file?

**Comment by Kiran-Serolla** [comment]
> Can you also add the cvs.router to the api-router file?

HI Benjamin,
I added the router  but hven't pushed 'api_routers.js' file. I thought it was not necessary to include it in the PR . Or should I include it in the PR?

**Comment by benna100** [comment]
I think you should include it :)

**Comment by Kiran-Serolla** [comment]
> Can you also add the cvs.router to the api-router file?

done!

**Review by benna100 — APPROVED** [review]
Looks good!

**Comment by benna100** [comment]
There is a merge conflict here

**Review by benna100 — APPROVED** [review]
Looks good :)

**Comment by Kiran-Serolla** [comment]
> > Can you also add the cvs.router to the api-router file?
> 
> HI Benjamin,
> I added the router but hven't pushed 'api_routers.js' file. I thought it was not necessary to include it in the PR . Or should I include it in the PR?

Can this be merged now?

**Pull request merged**
