### PR TITLE
Fix positioning of footer...

### PR DESCRIPTION
**Pull request by valmdz**
... so it stays at the bottom in all possible scenarios

# Description

Improved the responsiveness of the footer and set the position so it is always at the bottom

Fixes # (issue)

# How to test?

Please provide a short summary how your changes can be tested?

`npm run dev
`
https://user-images.githubusercontent.com/36211640/107572683-df6f4f80-6bec-11eb-940a-d105d979cadc.mp4

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by bytewiz — APPROVED** [review]
Looks good to me 👍

**Comment by KavyaReddy732** [comment]
i don't find anything that should be modified. everything looks fine

**Comment by pdsorensen** [comment]
@valmdz can you update this branch so the build step passes (and we can get it merged)? :)

**Comment by valmdz** [comment]
> @valmdz can you update this branch so the build step passes (and we can get it merged)? :)

updated ;) @pdsorensen

**Pull request merged**
