### PR TITLE
created button story using knobs

### PR DESCRIPTION
**Pull request by shruthidasarapu**
# Description
Created  button story

Fixes # (issue)
#issue 13 
# How to test?
npm run storybook

# Checklist

- [x ]  I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [x ] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Comment by pdsorensen** [comment]
Looks good to me. @benna100 do we use a style format like prettier? Otherwise i think this is ready to be merged, looking at the related issue.

**Review by pdsorensen — APPROVED** [review]
Looks good as a starting point. I think it needs to be a bit more flexible, e.g styles and button type, but let's take that in another PR.

**Comment by shruthidasarapu** [comment]
May i create one more PR with style

**Comment by pdsorensen** [comment]
@shruthidasarapu unfortunately i already merged it. Feel free to create another story/issue and then a new PR, and then i'll be happy to review that one too. Cheers,

**Comment by shruthidasarapu** [comment]
ok  but  how can i do? Can you explain me ?
Should i create another branch and do it again the same with styling and make a PR.

**Comment by pdsorensen** [comment]
That would be a good start yeah.

**Pull request merged**
